# # Volume
# binde =, XF86AudioLowerVolume, exec, pamixer -d 5 # decrease 5%
# binde =, XF86AudioRaiseVolume, exec, pamixer -i 5 # increase 5%
# bind =, XF86AudioMute, exec, pamixer -t # toggle mute/unmute

# Mic volume
# binde =SUPER,XF86AudioLowerVolume, exec, amixer -q set Dmic0 3%-
# binde =SUPER,XF86AudioRaiseVolume, exec, amixer -q set Dmic0 3%+
#binde =,XF86AudioMicMute, exec, amixer -q set Dmic0 toggle
# binde =,XF86AudioMicMute, exec, pamixer -d 5

#Screen brightness
# binde =,XF86MonBrightnessDown, exec, xbacklight -dec 5
# binde =,XF86MonBrightnessUp, exec, xbacklight -inc 5

# Shutdown menu
bind =SUPER,Delete,exec,rofi -show p -modi p:'~/.config/rofi/utils/rofi-power-menu --choices shutdown/lockscreen/reboot/suspend/logout --no-symbols'

# Media controls
# bind =, XF86PickupPhone, exec, playerctl previous
# bind =, XF86HangupPhone, exec, playerctl play-pause
# bind =, XF86Favorites, exec, playerctl next


